linux-firmware: add SRCREV_FORMAT
fix error of below:
	FetchError: Fetcher failure: The SRCREV_FORMAT variable must be set when multiple SCMs are used.